### ISSUE TITLE
Fails with json columns?

### ISSUE THREAD

**Issue by AdityaAnand1** [mla/pg_sample#20]
```
DBD::Pg::db do failed: ERROR:  could not identify an equality operator for type json
LINE 3:            SELECT DISTINCT t1.*
                                   ^ at ./pg_sample line 296.
        main::__ANON__("DBD::Pg::db do failed: ERROR:  could not identify an equality"..., DBI::db=HASH(0x55d7b81db5b0), undef) called at ./pg_sample line 644
```

**Comment by AdityaAnand1** [comment]
Any thoughts on how to fix this @mla?

**Comment by mla** [comment]
I haven't had a change to look in detail, but I did a bit of research and it sounds like jsonb type has equality operator defined but json does not.

We could potentially try and cast json -> jsonb? I'll try to put together a test case this week.

**Comment by mla** [comment]
One potential solution is just to convert your json columns to jsonb.

But if that isn't possible, I did manage to add equality operator to the json type with this:

```
create function json_lt(json, json)
returns boolean language sql immutable as $$
    select $1::jsonb < $2::jsonb
$$;

create function json_lte(json, json)
returns boolean language sql immutable as $$
    select $1::jsonb < $2::jsonb OR $1::jsonb = $2::jsonb
$$;

create function json_gt(json, json)
returns boolean language sql immutable as $$
    select $1::jsonb > $2::jsonb
$$;

create function json_gte(json, json)
returns boolean language sql immutable as $$
    select $1::jsonb > $2::jsonb OR $1::jsonb = $2::jsonb
$$;

create function json_eq(json, json)
returns boolean language sql immutable as $$
    select $1::jsonb = $2::jsonb
$$;


create operator < (leftarg = json, rightarg = json, procedure = json_lt);
create operator > (leftarg = json, rightarg = json, procedure = json_gt);
create operator >= (leftarg = json, rightarg = json, procedure = json_gte);
create operator <= (leftarg = json, rightarg = json, procedure = json_lte);
create operator = (leftarg = json, rightarg = json, procedure = json_eq);

create function jsoncmp(json, json)
returns integer language sql immutable as $$
    select case 
        when $1 = $2 then 0
        when $1 < $2 then -1
        else 1
    end
$$;

create operator class json_ops
  default for type json using btree AS
    operator 1 <,
    operator 2 <=,
    operator 3 =,
    operator 4 >=,
    operator 5 >,
    function 1 jsoncmp(json, json)
;
```

I added a test and it seemed to work.

**Comment by mariano-balto** [comment]
hello @mla, it seems that this problem still persists with (at least with master)

Is there a way I can help testing this?

**Comment by mla** [comment]
jsonb, eh? Hrm. I've never hit the problem with jsonb. And the error message says "for type json"
Can you try applying those json comparison operators ^^^ and see if it resolves it?

Otherwise, yeah, if you could produce a small standalone table that can trigger the problem, that would be great.

**Comment by mariano-balto** [comment]
@mla my apologies, you were absolutely right. After converting the column from`json` to `jsonb` `pg_sample` worked like a charm.

Thanks again

**Comment by mariano-balto** [comment]
@mla Is there a workaround in case that converting the type of the column from `json` to `jsonb` is not possible?

**Comment by mla** [comment]
Defining the operators above worked perfectly for me. 

> How can I test this?

Do you have a working test instance you can apply those changes to? That's what I did. And then I eventually applied them to our production dbs.

**Comment by mariano-balto** [comment]
hey @mla after executing the operators I can see this in the logs:

```
ERROR:  operator does not exist: json = json at character 34
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
QUERY:
	    select case
	        when $1 = $2 then 0
	        when $1 < $2 then -1
	        else 1
	    end

CONTEXT:  SQL function "jsoncmp" during startup
```

postgres version: 9.6.21

By any chance, you know what could be the problem?

thanks!

**Comment by mariano-balto** [comment]
i think i fugured it out, i was just missing the cast

```
select case
	        when $1::jsonb = $2::jsonb then 0
	        when $1::jsonb < $2::jsonb then -1
	        else 1
	    end
```

**Comment by mla** [comment]
I added the code for the json equality operator under /contrib and am closing this issue now.
