### ISSUE TITLE
Docker: Can't exec "pg_dump"

### ISSUE THREAD

**Issue by jacektrocinski** [mla/pg_sample#26]
`pg_sample` is returning the following error when I run it from within the Docker container:

```console
root@docker-desktop:/pg_sample# ./pg_sample dev-db --host=localhost --port=63123 -U postgres -W pass --limit=20 --verbose --keep
Server encoding is UTF8
Client encoding is UTF8
Exporting schema
Can't exec "pg_dump": No such file or directory at ./pg_sample line 471.
command 'pg_dump --schema-only' failed: -1 at ./pg_sample line 471.
Done.
```

**Comment by mla** [comment]
Are you using the master branch? See if "dev" branch works for you? There were some dockerfile improvements on there, I believe.

**Comment by jacektrocinski** [comment]
The `dev` branch Docker file worked for me, thanks!

On a different note, the `-p` argument didn’t work for me though `--port` worked fine.

**Comment by mla** [comment]
Thank you @jacektrocinski. -p should be fixed now dev branch now
