### ISSUE TITLE
Error using --random parameter

### ISSUE THREAD

**Issue by luizm** [mla/pg_sample#36]
Hey

When I have a table with less than 100 records and use the `--random` parameter, I get this error:

```
[limit] .* = 100
Creating table "_pg_sample"."test" DBD::Pg::db do failed: ERROR:  sample percentage must be between 0 and 100 at pg_sample line 300.
	main::__ANON__("DBD::Pg::db do failed: ERROR:  sample percentage must be betw"..., DBI::db=HASH(0xaaab11eba948), undef) called at pg_sample line 572
Dropping sample schema _pg_sample
```

Any thoughts? thank you

**Comment by mla** [comment]
Looks like a bug. Please pull the latest changes on dev branch. I think it's fixed there now.

**Comment by luizm** [comment]
It works @mla thank you soo much for the quick reply

when it could be merged to master? :)

**Comment by mla** [comment]
Great. I'll shoot for tomorrow morning.

**Comment by luizm** [comment]
> Great. I'll shoot for tomorrow morning.

Ok.. thank again :)

**Comment by mla** [comment]
1.13 is live :+1:
