### ISSUE TITLE
Version 1.13 missing from github releases

### ISSUE THREAD

**Issue by stephenemslie** [mla/pg_sample#39]
Branch `release/1.13` seems to have been merged to master in [this commit](https://github.com/mla/pg_sample/commit/c9665a9fab4976327b08e28392357e57d6f0a796), but 1.12 is shown as the latest release on Github.

Should a new release be made?

**Comment by mla** [comment]
>  Should a new release be made?

Yes! Forgot to do that.

**Comment by mla** [comment]
1.13 release created
