### ISSUE TITLE
psql:mini.sql:254159: ERROR:  permission denied: "RI_ConstraintTrigger_c_11890996" is a system trigger

### ISSUE THREAD

**Issue by piqoni** [mla/pg_sample#43]
Great tool! ✋ 
Im facing the following issue when trying to load, Im on PG 14, Im running this command (mini.sql generated by pg_sample).
1. set session_replication_role = replica;
(to avoid integrity checks during inserts)
2. Then I run:
 psql -U postgres -d mini -f mini.sql

and I get a lot of errors: psql:mini.sql:254159: ERROR:  permission denied: "RI_ConstraintTrigger_c_11890996" is a system trigger  

and before that a lot of integrity errors. Any suggestions?

**Comment by mla** [comment]
I have not seen that before.

Note that pg_sample does emit a DISABLE TRIGGER ALL for all tables are part of the sample.
Take a look at your mini.sql and you should see the DISABLE TRIGGERs in there.

Do you see a reference to that RI_Constraint in mini.sql? Maybe try removing the DISABLE TRIGGER statements in there just to see?

**Comment by mla** [comment]
@piqoni
https://www.endpointdev.com/blog/2012/10/postgres-system-triggers-error/

**Comment by piqoni** [comment]
Thank you, It's definitely related to trying to load on an AWS RDS without being superuser. 
I tried on my local and it works fine so I think we can close this ticket. 

Thank you for this tool, I haven't made it work yet in terms of application (becuase need to identify which configuration tables need to be dumped in full). 

If this tool ensures indeed referential integrity its the bomb!
