### ISSUE TITLE
sample_schema table naming greater than 63 characters

### ISSUE THREAD

**Issue by chadhoyt** [mla/pg_sample#45]
Hi @mla  This tool is great for some of our smaller databases.  Thanks!

However, with a larger data warehouse (~2000 tables) we have 31 of those tables where the combination of the schema_name and table_name bombs on the population of the sample_schema due to 63 character limit imposed by the postgresql Max Identifier Length (NAMEDATALEN) and I suspect will also have issues on retrieval of the sample data for COPY <table> FROM stdin portion of sampling.

Error that I'm getting on the sample schema population (using "--sample_schema pgs" option): 

```
Creating table "pgs"."marketing_analytics_transunion_factortrust_combined_ccb_scoring_legacy" 1000
Creating table "pgs"."marketing_analytics_transunion_factortrust_combined_ccb_scoring_python38" DBD::Pg::db do failed: ERROR:  relation "marketing_analytics_transunion_factortrust_combined_ccb_scoring" already exists at ./pg_sample line 300.
        main::__ANON__("DBD::Pg::db do failed: ERROR:  relation \"marketing_analytics_"..., DBI::db=HASH(0x7fc45e828930), undef) called at ./pg_sample line 634
```

Using the --keep option, I was able to see that the previous table name (_legacy suffix) gets truncated to "marketing_analytics_transunion_factortrust_combined_ccb_scoring" at 63 characters and then the subsequent table name is same name except for the  _python38 suffix and thus appears that the table already exists.

Do you have ideas and/or a potential patch that could address this?  I've tried using `--limit="marketing_analytics.transunion_\d+=0"` but that still tries to create the schema.  I could skip this marketing_analytics schema by running through the others individually with --schema option but that would only help for 6 of the 31 affected.  The other 25 are dispersed across 9 other schemas.

Thanks for any help you can provide.

**Comment by mla** [comment]
Hello!

Wow, yes, I've never seen that. This patch requires that you have Digest::MD5 module installed. Lightly tested but it appears to work (I recreated your schema/table names locally).

```
diff --git a/pg_sample b/pg_sample
index e44a522..87b0cfd 100755
--- a/pg_sample
+++ b/pg_sample
@@ -200,6 +200,7 @@ use Carp;
 use Getopt::Long qw/ GetOptions :config no_ignore_case /;
 use DBI;
 use DBD::Pg 2.0.0;
+use Digest::MD5 qw/ md5_hex /;
 
 $SIG{TERM} = $SIG{INT} = $SIG{QUIT} = $SIG{HUP} = sub {
   my $signal = shift;
@@ -372,7 +373,7 @@ sub quote_constant (@) {
 sub sample_table ($) {
   my $table = shift;
 
-  my $sample_table = join '_', $table->schema || 'public', $table->table;
+  my $sample_table = md5_hex($table->schema || 'public', $table->table);
   return Table->new($opt{sample_schema}, $sample_table);
 }
 
```

It makes the sample tables more difficult to assess, so I'll prob try to more nuanced approach where we only resort to something like this if we hit the length limit.

**Comment by mla** [comment]
@chadhoyt pls try my changes on the dev branch. I removed the Digest::MD5 dependency. It's now prepending a unique sequence onto each sample table name.

**Comment by chadhoyt** [comment]
@mla thanks for the quick response.  I applied the patch but started to notice other issues that weren't making sense when I saw the suggestion to switch to dev branch.  However, with dev branch I had to install Readonly module that I hadn't needed on master branch.

`sudo perl -MCPAN -e 'install Readonly'`

otherwise, was getting: 
```
Can't locate Readonly.pm in @INC ...   ./pg_sample line 203.
```

Once completed that install, it appears to execute again but I'm still seeing similar issues to the patch version with no obvious explanation yet.  These are interspersed before and after the previous reported tables where I wasn't seeing on the unpatched master.  Good news though is that the affected tables seem to be good

Issue output:
```
ERROR:  relation "marketing_analytics.preapprovals92" does not exist
Time: 0.276 ms
invalid command \N
invalid command \N
invalid command \N
<... MANY OF THESE REPEAT ...>
invalid command \N
invalid command \N
Exporting data from "pgs"."004d__marketing_analytics_pull_exp_attributes_exp_110" (0)
Exporting data from "pgs"."004e__marketing_analytics_retention_data_for_study" (100)
invalid command \.
ERROR:  syntax error at or near "Nabil"
LINE 1: Nabil J Vargha Nabil J Vargha 1633  CENTRAL  AVE APT 2 Alame...
        ^
Time: 0.886 ms
invalid command \.
ERROR:  syntax error at or near "1"
LINE 1: 1 EXP Experian
        ^
Time: 0.233 ms
invalid command \.
Exporting data from "pgs"."004f__marketing_analytics_selection_group_send" (28)
COPY 100
```

Following success output for the 63 max length tables originally reported:
```
Time: 106.151 ms
Exporting data from "pgs"."005d__marketing_analytics_transunion_factortrust_combined_ccb_s" (100)
COPY 100
Time: 105.532 ms
Exporting data from "pgs"."005e__marketing_analytics_transunion_factortrust_combined_ccb_s" (100)
COPY 100
Time: 104.357 ms
```

**Comment by mla** [comment]
I removed the Readonly dependency. I thought that was a standard module.

I'll have to investigate why you're now seeing the other errors. Seems to be working the same for me.
The same table names should be arbitrary. It looks like maybe something isn't escaped correctly now or something. Hrm.

Will try to reproduce.

**Comment by mla** [comment]
You actually have a marketing_analytics.preapprovals92 table?

**Comment by mla** [comment]
Could you retry master and make sure those errors are not there?

**Comment by chadhoyt** [comment]
@mla good news, your latest dev branch is working for me end-to-end.  

After reviewing again on master I found three things going on, my side.  First, that I wasn't seeing some of the prior `ERROR:  relation "<schema>.<tablename>" does not exist` messages (perhaps I didn't have --verbose option set at that point.  Second, some of them were related to --schema option and in my attempt to isolate the above max length issue had set filter to only `marketing_analytics` schema (cross-schema dependencies issue?).  Third, I had a few configuration issues on my target instance for things like missing roles, w.r.t assigned owner on objects etc..  Once addressed, I've been able to repeatedly run without issue from this dev branch (and to the point of above issue on master).

Thank you so much!

**Comment by chadhoyt** [comment]
> You actually have a marketing_analytics.preapprovals92 table?

yes, we do have this table but was related to findings on my side.

**Comment by mla** [comment]
> @mla good news, your latest dev branch is working for me end-to-end.

Fantastic. ok, i'll see about adding some tests for this and get a new release out. Thank you for reporting!

**Comment by mla** [comment]
These changes are in v1.16 release. Thank you, @chadhoyt !
