### ISSUE TITLE
psql invalid command \n or \N

### ISSUE THREAD

**Issue by fegmorte** [mla/pg_sample#49]
Hi,

The output generated from our database contains lot of `\N` or `\n` characters.
Those characters are interpreted by psql when i try to import the dump in a new database.

The encoding between the source and the target is utf-8.

Is there a way to avoid this error ?

Thank you

**Comment by mla** [comment]
Hey @fegmorte. Sorry for the delay in responding.

What is the actual error? Because, yes, I would expect lots of \N and \n values in the output, but psql should interpret those fine.

**Comment by mla** [comment]
Ah, maybe this is the issue?

https://stackoverflow.com/questions/20427689/psql-invalid-command-n-while-restore-sql

Try setting that -v value:

psql -v ON_ERROR_STOP=1

I always use that. I'll update the docs to include that.

**Comment by fegmorte** [comment]
Hi @mla 

Thank you for your answer.

Sorry i didn't attach the error message but it is the one that you find in SO.
```invalid command \N```

I have seen this solution but it seems to only stop the import on the first error as it said in SO:
```Is possible to switch psql to "stop on first error" mode and to find error```

I will try `-v ON_ERROR_STOP=1` and i will give you a feedback.

**Comment by fegmorte** [comment]
Thank you @mla ! it was due to a lack of extension `hstore`.
Sorry for wasting your time :)

**Comment by mla** [comment]
> Sorry for wasting your time :)

Not at all. Glad you resolved it and I think it will be a good improvement to the synopsis to mention the ON_ERROR_STOP=1 flag.

Happy new year!
