### ISSUE TITLE
[SOLVED] ERROR:  could not identify an equality operator for type json

### ISSUE THREAD

**Issue by aarona** [mla/pg_sample#55]
Given the following script:

```pg_sample -a --ordered \
  mydb | psql -v ON_ERROR_STOP=1 mydb-sample
```

I received an error (see below). I redacted a bunch of private information about my company's schema. I hope that I'm providing enough information for you to get an idea of what's causing this. Adding a `--trace` option gave me the following:

```
    !! ERROR: 7 "ERROR:  could not identify an equality operator for type json
LINE 3: ...[REDACTED COLUMN NAMES], t1."argume...
                                    ^" (err#0)
    <- do("
      INSERT INTO "_pg_sample"."004d__public_[redacted_table_A]"
           SELECT DISTINCT t1."id", [REDACTING COLUMNS TO PROTECT PRIVATE INFORMATION],
                  t1."arguments", [REDACTING COLUMNS TO PROTECT PRIVATE INFORMATION]
             FROM [redacted_table_A] t1
                  JOIN "_pg_sample"."004a__public_[redacted_table_B]" f1 ON (f1.[redacted_fk_column_id] = t1.id)
                  LEFT JOIN "_pg_sample"."004d__public_[redacted_table_A]" s1 ON (t1.id = s1.id)
            WHERE s1.id IS NULL
    ")= ( undef ) [1 items] at pg_sample line 836
    -> HandleError on DBI::db=HASH(0x5f0c02df48d0) via CODE(0x5f0c02d38f60) (undef)
    <- can(CARP_TRACE) = 0 (? 0)
DBD::Pg::db do failed: ERROR:  could not identify an equality operator for type json
LINE 3: ...[REDACTED COLUMN NAMES], t1."argume...
                                    ^ at ./pg_sample line 336.
	main::__ANON__("DBD::Pg::db do failed: ERROR:  could not identify an equality"..., DBI::db=HASH(0x5f0c02df4ae0), undef) called at ./pg_sample line 836
       ERROR: 7 "ERROR:  could not identify an equality operator for type json
LINE 3: ...[REDACTED COLUMN NAMES], t1."argume...
                                    ^" (err#0)
    <- DESTROY(DBI::st=HASH(0x5f0c02bca838))= ( undef ) [1 items] at Carp.pm line 290
    !! The ERROR '7' was CLEARED by call to do method
    <- do('DROP SCHEMA _pg_sample CASCADE')= ( '0E0' ) [1 items] at pg_sample line 924
!   <- DESTROY(DBI::db=HASH(0x5f0c02df4ae0))= ( undef ) [1 items] during global destruction
```

the `t1.arguments` column is a `json` data type and having PGAdmin generate a `CREATE TABLE` script for the table that contains the `arguments` column gives the following information on that particular column:

```
arguments json NOT NULL DEFAULT '{}'::json,
```

I think this should be enough information to recreate the problem. It seems pretty straightforward: JSON columns can't be compared for equality it seems? Which would make sense unless you could get some kind of hash value of the object to compare against.

Would omitting the `DISTINCT` statement for tables with these column types be a good work-around in this situation?

Probably a table with a `json` column should probably be enough to recreate the error, right? If you need, I can give more information and maybe some sample data in the `arguments` column itself but I want to try to avoid that unless I can get permission first.

**Comment by mla** [comment]
Hey @aarona aarona, see if the add_json_equality_operator.sql script under contrib/ works for you.

**Comment by aarona** [comment]
Running that sql file on my original database fixes that issue. I've got a new one related to a sequence not being found (but I can see it in PGAdmin4).

Is this fix documented somewhere in a trouble shooting section? I didn't see that anywhere. If you'd like, I could create a `Troubleshooting` section on the `README.md` file or create a separate trouble shooting markdown file that is linked to from the `README` as a PR if you'd like.

**Comment by mla** [comment]
> Running that sql file on my original database fixes that issue. I've got a new one related to a sequence not being found (but I can see it in PGAdmin4).
> 
> Is this fix documented somewhere in a trouble shooting section? I didn't see that anywhere. If you'd like, I could create a `Troubleshooting` section on the `README.md` file or create a separate trouble shooting markdown file that is linked to from the `README` as a PR if you'd like.

That would be excellent!
