### ISSUE TITLE
wildcards not working as expected in "--limit"

### ISSUE THREAD

**Issue by ElhanM** [mla/pg_sample#59]
What I am trying to do:

```
# include 50% of rows from all tables in the public schema
--limit="public.* = 50%"
```

Does not seem to do what you would expect it to. I tried doing 100% as well, was not able to export all of my data that way.

What is going on here?

@mla

**Comment by mla** [comment]
Hey @ElhanM. Did it end up working for you?

**Comment by ElhanM** [comment]
Yup, I played around with it and got it to work

Don't know if it didn't work initially because of the spaces in the regex, or because I was trying to restore the data to a non-empty db.

Thank you for the response anyway.
