### ISSUE TITLE
DBD::Pg::db table_info failed: ERROR:

### ISSUE THREAD

**Issue by santanab** [mla/pg_sample#6]
DBD::Pg::db table_info failed: ERROR:  column t.spclocation does not exist
LINE 11: ...t(t.spcname) AS "pg_tablespace_name", quote_ident(t.spclocat...
                                                              ^ at /usr/bin/pg_sample line 296
	main::__ANON__('DBD::Pg::db table_info failed: ERROR:  column t.spclocation d...', 'DBI::db=HASH(0x1bc4eb8)', 'DBI::st=HASH(0x1bc5398)') called at /usr/bin/pg_sample line 499

Maybe this is a known issue, but I don't know what can I do with this error, I know that the column spclocation doesn't exist at pg_tablespace since postgresql 9.2 and I using postgresql 9.5. So, ¿what can I do to resolve that?

Thanks.

Packages installed:

perl-DBD-Pg-2.17.1
perl-DBI-1.622-1
postgresql 9.5 

I've downloaded pg_sample from yum. Pg_sample version 1.09

**Comment by mla** [comment]
Can you try a more recent version of DBD::Pg? I see no reference to spclocation in pg_sample itself, so I'm guessing it's originating from DBD::Pg

The yum package should maybe require a higher DBD::Pg for use with postgresql 9.5? I haven't used or seen the yum package.

**Comment by mla** [comment]
Looks like we did hit this problem before:
https://github.com/mla/pg_sample/issues/3

And here is a discussion of the issue on DBD::Pg:
https://rt.cpan.org/Public/Bug/Display.html?id=88439

**Comment by santanab** [comment]
Thanks. The problem was with the version of perl-dbd-pg, so I tried with the 2.19.3 version but I get the following error: 

DBD::Pg object version 0 does not match bootstrap parameter 2.19.3 at /usr/lib64/perl5/DynaLoader.pm 

So, I had to go into the /usr/lib64/perl5/vendor_perl/DBD/Pg.pm and copy the lines:

_** if ($dbh->{private_dbdpg}{version} >= 90200) {
         $showtablespace = ', quote_ident(t.spcname) AS "pg_tablespace_name", quote_ident(pg_tablespace_location(t.oid)) AS "pg_tablespace_location"';
 }**_

And then install again the perl-dbd-pg 2.17.. version. and I added the lines that I copied from the /usr/lib64/perl5/vendor_perl/DBD/Pg.pm of the other version. And pg_sample works perfectly. 

 my $showtablespace = ', quote_ident(t.spcname) AS "pg_tablespace_name", quote_ident(t.spclocation) AS "pg_tablespace_location"';
##taken from perl-dbd-pg 2.19.3
                        if ($dbh->{private_dbdpg}{version} >= 90200) {
                                            $showtablespace = ', quote_ident(t.spcname) AS "pg_tablespace_name", quote_ident(pg_tablespace_location(t.oid)) AS "pg_tablespace_location"';
                         }
