### ISSUE TITLE
pg_sample --no-privileges

### ISSUE THREAD

**Issue by lpossamai** [mla/pg_sample#7]
Hi there,

I tried to use pg_sample with --no-privileges option but it does not work.

Is this option available with pg_sample?

Here are some errors:

psql:/var/lib/postgresql/all_data.sql:29313: ERROR:  role "tester" does not exist
psql:/var/lib/postgresql/all_data.sql:51634: ERROR:  syntax error at or near "s"
LINE 1: s:7:"deleted";
psql:/var/lib/postgresql/all_data.sql:56352: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56353: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56354: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56355: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56356: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56357: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56358: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56359: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56360: invalid command \N
psql:/var/lib/postgresql/all_data.sql:56361: invalid command \N

Thanks
Lucas

**Comment by mla** [comment]
Hello! Sorry for the delay. I was traveling.

Looks like we don't support the --no-privileges option currently. I just added it to the dev branch:
https://github.com/mla/pg_sample/blob/dev/pg_sample

Perhaps we should be passing any "unknown" options on through pg_sample. That would probably be a cleaner solution. But this should work for now.

**Comment by mla** [comment]
This change is on master
